import { StyleSheet, Platform } from 'react-native';
export const styles = StyleSheet.create({
  doctorName: { color: '#059669', fontSize: 16, fontWeight: '500', marginTop: 4 },
  empty: { textAlign: 'center', marginTop: 50, color: '#94a3b8', fontStyle: 'italic' },
  tabHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 15 },
  refreshBtn: { backgroundColor: '#e0f2fe', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  refreshText: { color: '#0284c7', fontWeight: 'bold', fontSize: 12 },
  agendaCard: { backgroundColor: '#fff', padding: 15, marginHorizontal: 15, marginBottom: 10, borderRadius: 10, borderLeftWidth: 5, borderLeftColor: '#0ea5e9', elevation: 1 },
  agendaTime: { color: '#0ea5e9', fontWeight: 'bold', marginBottom: 5 },
  agendaPatient: { fontSize: 16, fontWeight: 'bold', color: '#1e293b' },
  agendaType: { color: '#64748b', fontSize: 14, marginTop: 5 },
  searchContainer: { padding: 15, backgroundColor: '#fff', marginBottom: 5 },
  searchInput: { backgroundColor: '#f1f5f9', padding: 12, borderRadius: 8, fontSize: 16, marginBottom: 10 },
  filterRow: { flexDirection: 'row', gap: 10 },
  filterChip: { paddingHorizontal: 15, paddingVertical: 6, borderRadius: 20, backgroundColor: '#e2e8f0' },
  filterChipActive: { backgroundColor: '#3b82f6' },
  chipText: { color: '#64748b', fontWeight: '500' },
  chipTextActive: { color: '#fff', fontWeight: 'bold' },
  row: { flexDirection: 'row', backgroundColor: '#fff', padding: 15, marginHorizontal: 10, marginBottom: 8, borderRadius: 12, alignItems: 'center', elevation: 1 },
  rowRevisado: { opacity: 0.6, backgroundColor: '#f1f5f9' },
  rowInfo: { flex: 1 },
  rowName: { fontSize: 16, fontWeight: 'bold', color: '#1e293b' },
  rowDoc: { fontSize: 12, color: '#64748b' },
  rowSymptom: { fontSize: 14, color: '#475569', marginTop: 4 },
  actionBtn: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  btnPendiente: { backgroundColor: '#fee2e2' },
  btnRevisado: { backgroundColor: '#dcfce7' },
  tabSelector: { flexDirection: 'row', backgroundColor: 'white', paddingHorizontal: 10, paddingBottom: 10, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 3, elevation: 2 },
  tabButton: { flex: 1, paddingVertical: 12, alignItems: 'center', borderBottomWidth: 3, borderBottomColor: 'transparent' },
  tabButtonActive: { borderBottomColor: '#007AFF' },
  tabText: { fontSize: 16, color: '#6b7280', fontWeight: '500' },
  tabTextActive: { color: '#007AFF', fontWeight: 'bold' },

  // Contenedor principal de cada pestaÃ±a
  tabContent: { flex: 1, padding: 20 },
  calendarInfoBox: { backgroundColor: '#e0f2fe', padding: 15, borderRadius: 10, marginBottom: 20, borderWidth: 1, borderColor: '#bae6fd' },
  calendarInfoText: { color: '#0369a1', fontSize: 14, lineHeight: 20 },
  syncButton: { backgroundColor: '#4285F4', padding: 15, borderRadius: 10, alignItems: 'center', flexDirection: 'row', justifyContent: 'center' },
  syncButtonDisabled: { backgroundColor: '#9ca3af' },
  syncButtonText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
  upcomingAppointmentsBox: { flex: 1, backgroundColor: 'white', marginTop: 20, borderRadius: 10, borderWidth: 1, borderColor: '#e5e7eb' },
  sessionInfo: {
    fontSize: 14,
    color: '#059669',
    marginBottom: 15,
    fontWeight: '500'
  },
  statusBox: { padding: 12, borderRadius: 8, marginBottom: 15 },
  statusSuccess: { backgroundColor: '#dcfce7', borderWidth: 1, borderColor: '#bbf7d0' },
  statusError: { backgroundColor: '#fee2e2', borderWidth: 1, borderColor: '#fecaca' },
  statusText: { fontWeight: '600', textAlign: 'center' },
  statusTextSuccess: { color: '#166534' },
  statusTextError: { color: '#991b1b' },
  characterCount: { textAlign: 'right', color: '#9ca3af', fontSize: 12, marginTop: 5, marginRight: 5 },
  characterCountLimit: { color: '#dc2626', fontWeight: 'bold' }, // Se pone rojo si llega al lÃ­mite
  button: { backgroundColor: '#007AFF', padding: 15, borderRadius: 10, marginTop: 20, alignItems: 'center' },
  buttonLoading: { backgroundColor: '#93c5fd' },
  inputDisabled: { backgroundColor: '#f3f4f6', color: '#9ca3af' },
  reportCard: { backgroundColor: '#fef3c7', padding: 15, borderRadius: 8, marginBottom: 15, borderWidth: 1, borderColor: '#fde68a' },
  reportHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  weekBadge: { backgroundColor: '#f59e0b', color: 'white', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, fontSize: 12, fontWeight: 'bold' },
  symptomsText: { color: '#78350f', fontSize: 15, fontStyle: 'italic', marginBottom: 12 },

  // BotÃ³n de revisar
  checkButton: { backgroundColor: '#059669', padding: 10, borderRadius: 6, alignItems: 'center' },
  checkButtonText: { color: 'white', fontWeight: 'bold', fontSize: 14 },
  statsCard: {
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3
  },
  emptyText: { textAlign: 'center', color: '#999', marginTop: 10 },
  doctorContainer: {
    flex: 1,
    backgroundColor: '#f3f4f6',
  },
  welcomeText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  idText: {
    fontSize: 14,
    color: '#6b7280',
    marginTop: 4,
  },
  scrollContent: {
    padding: 16,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
    color: '#374151',
  },
  appointmentItem: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  patientName: {
    fontSize: 16,
    fontWeight: '600',
  },
  timeText: {
    color: '#6b7280',
  },
  actionButton: {
    marginTop: 20,
    backgroundColor: '#ef4444',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  safe: {
    flex: 1,
    backgroundColor: '#f7f7f7',
  },
  screen: {
    flex: 1,
    backgroundColor: '#f7f7f7',
  },
  content: {
    paddingHorizontal: 18,
    paddingBottom: 120,
    paddingTop: 10,
  },
  idContent: {
    paddingHorizontal: 24,
    paddingBottom: 120,
    paddingTop: 18,
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 6,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0b1b33',
  },
  subtitle: {
    marginTop: 6,
    fontSize: 18,
    color: '#1f2937',
    lineHeight: 24,
  },
  sectionLabel: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0b1b33',
  },
  normalText: {
    fontSize: 18,
    color: '#111827',
    lineHeight: 24,
    marginTop: 10,
  },
  bigText: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0b1b33',
    marginTop: 6,
  },
  bold: { fontWeight: '800' },
  disclaimer: {
    marginTop: 16,
    fontSize: 14,
    color: '#6b7280',
    lineHeight: 20,
  },
  errorText: {
    marginTop: 10,
    fontSize: 16,
    color: '#b91c1c',
    fontWeight: '700',
  },
  btnBase: {
    borderRadius: 14,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginTop: 12,
  },
  btnPrimary: { backgroundColor: '#0b74ff' },
  btnDanger: { backgroundColor: '#dc2626' },
  btnMuted: { backgroundColor: '#e5e7eb' },
  btnDisabled: { opacity: 0.6 },
  btnPressed: { transform: [{ scale: 0.99 }] },
  btnText: { color: '#0b1b33' },
  btnDangerText: { color: '#ffffff' },
  btnLabel: {
    fontSize: 20,
    fontWeight: '800',
  },
  docGrid: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 10,
    flexWrap: 'wrap',
  },
  docOption: {
    flexBasis: '46%',
    height: 66,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docOptionSelected: {
    borderColor: '#0b74ff',
    backgroundColor: '#e0f2fe',
  },
  docOptionText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0b1b33',
  },
  docOptionTextSelected: {
    color: '#0b74ff',
  },
  input: {
    height: 56,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    paddingHorizontal: 16,
    fontSize: 20,
    color: '#0b1b33',
  },
  serviceCard: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
  },
  serviceCardInner: {
    minHeight: 92,
    justifyContent: 'center',
  },
  serviceTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0b1b33',
  },
  serviceSubtitle: {
    marginTop: 6,
    fontSize: 16,
    color: '#374151',
    lineHeight: 22,
  },
  cardPressed: { opacity: 0.9 },
  sectionDivider: {
    height: 22,
  },
  rowCard: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
    marginTop: 12,
  },
  rowCardPressed: {
    borderColor: '#93c5fd',
    backgroundColor: '#eff6ff',
  },
  rowTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0b1b33',
  },
  rowSubtitle: {
    marginTop: 6,
    fontSize: 16,
    color: '#4b5563',
    lineHeight: 22,
  },
  badgeOk: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: '#dcfce7',
    color: '#166534',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontWeight: '900',
    fontSize: 14,
  },
  badgeMuted: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: '#f3f4f6',
    color: '#374151',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontWeight: '900',
    fontSize: 14,
  },
  emergencyFab: {
    position: 'absolute',
    right: 14,
    bottom: 18,
    backgroundColor: '#dc2626',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 999,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  emergencyFabPressed: { opacity: 0.9 },
  emergencyFabText: {
    color: '#ffffff',
    fontWeight: '900',
    fontSize: 14,
    letterSpacing: 0.2,
  },
  hospitalCard: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
    marginTop: 12,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 10,
    gap: 10,
  },
  bulletDot: {
    fontSize: 18,
    lineHeight: 24,
    color: '#0b74ff',
  },
  documentMock: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
    minHeight: 260,
    justifyContent: 'center',
  },
  documentTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0b1b33',
  },
  documentText: {
    marginTop: 10,
    fontSize: 18,
    color: '#111827',
    lineHeight: 24,
  },
  homeHeader: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
  },
  homeHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  homeHeaderIcon: {
    fontSize: 28,
    color: '#0b74ff',
  },
  homeHeaderTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0b1b33',
  },
  homeHeaderProfile: {
    backgroundColor: '#e0ecff',
    padding: 8,
    borderRadius: 999,
  },
  homeHeaderProfileIcon: {
    fontSize: 20,
  },
  homeContent: {
    paddingHorizontal: 18,
    paddingBottom: 120,
    paddingTop: 12,
    gap: 16,
  },
  homeWelcomeTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#0b1b33',
    marginBottom: 2,
  },
  homeWelcomeSubtitle: {
    fontSize: 18,
    color: '#4b5563',
  },
  homeCardsGrid: {
    marginTop: 12,
    gap: 14,
  },
  homeServiceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
  },
  homeServiceIconBox: {
    backgroundColor: '#e0ecff',
    padding: 14,
    borderRadius: 18,
    marginRight: 14,
  },
  homeServiceIcon: {
    fontSize: 26,
  },
  homeServiceTextBox: {
    flex: 1,
  },
  homeServiceTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0b1b33',
  },
  homeServiceSubtitle: {
    marginTop: 4,
    fontSize: 16,
    color: '#4b5563',
  },
  homeInfoBox: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 18,
    backgroundColor: '#f3f4f6',
  },
  homeInfoIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  homeInfoText: {
    flex: 1,
    fontSize: 14,
    color: '#4b5563',
  },
  pickHeader: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  pickBackBtn: {
    width: 44,
    height: 44,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickBackBtnPressed: { backgroundColor: '#f3f4f6' },
  pickBackIcon: {
    fontSize: 28,
    fontWeight: '900',
    color: '#0b1b33',
    marginTop: -2,
  },
  pickHeaderTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0b1b33',
  },
  pickContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 120,
    gap: 14,
  },
  pickInfoBox: {
    borderRadius: 18,
    backgroundColor: '#e0ecff',
    borderWidth: 1,
    borderColor: '#cfe2ff',
    padding: 14,
  },
  pickInfoTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0b74ff',
  },
  pickInfoText: {
    marginTop: 6,
    fontSize: 14,
    color: '#4b5563',
    lineHeight: 20,
  },
  pickCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  pickCardPressed: {
    transform: [{ scale: 0.99 }],
    borderColor: '#93c5fd',
    backgroundColor: '#eff6ff',
  },
  pickIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickIcon: {
    fontSize: 28,
  },
  pickCardText: {
    flex: 1,
  },
  pickCardTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0b1b33',
  },
  pickCardSubtitle: {
    marginTop: 4,
    fontSize: 14,
    color: '#4b5563',
  },
  pickChevron: {
    fontSize: 28,
    fontWeight: '900',
    color: '#cbd5e1',
    marginLeft: 6,
    marginTop: -2,
  },
  appointmentContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 180,
    gap: 16,
  },
  appointmentDoctorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 18,
    backgroundColor: '#e0f2fe',
    borderWidth: 1,
    borderColor: '#bae6fd',
    padding: 14,
  },
  appointmentAvatar: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: '#0b74ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appointmentAvatarText: {
    color: '#ffffff',
    fontWeight: '900',
    fontSize: 16,
    letterSpacing: 0.4,
  },
  appointmentDoctorName: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0b1b33',
  },
  appointmentDoctorMeta: {
    marginTop: 4,
    fontSize: 14,
    color: '#4b5563',
  },
  appointmentStepTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0b1b33',
    marginTop: 4,
  },
  appointmentCalendarCard: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
  },
  appointmentMonthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  appointmentMonthBtn: {
    width: 44,
    height: 44,
    borderRadius: 999,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appointmentMonthBtnText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0b1b33',
    marginTop: -2,
  },
  appointmentMonthTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0b1b33',
  },
  appointmentCalendarHint: {
    fontSize: 14,
    color: '#6b7280',
    lineHeight: 20,
  },
  appointmentSlotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  appointmentSlotBtn: {
    width: '48%',
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appointmentSlotBtnSelected: {
    borderColor: '#0b74ff',
    backgroundColor: '#e0ecff',
  },
  appointmentSlotText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0b1b33',
  },
  appointmentSlotTextSelected: {
    color: '#0b74ff',
  },
  appointmentSlotSubtext: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '800',
    color: '#6b7280',
  },
  appointmentSlotSubtextSelected: {
    color: '#0b74ff',
  },
  appointmentInfoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 18,
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#fbbf24',
    padding: 12,
  },
  appointmentInfoIcon: {
    fontSize: 18,
  },
  appointmentInfoText: {
    flex: 1,
    fontSize: 14,
    color: '#92400e',
    lineHeight: 20,
    fontWeight: '600',
  },
  appointmentFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  appointmentConfirmBtn: {
    height: 72,
    borderRadius: 18,
    backgroundColor: '#0b74ff',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    shadowColor: '#0b74ff',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  appointmentConfirmText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
  },
  appointmentConfirmIcon: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
    marginTop: -2,
  },
  resultsHeader: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  resultsHeaderBtn: {
    width: 44,
    height: 44,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultsHeaderBtnText: {
    fontSize: 28,
    fontWeight: '900',
    color: '#0b1b33',
    marginTop: -2,
  },
  resultsHeaderTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0b1b33',
  },
  resultsHeaderBell: {
    fontSize: 18,
  },
  resultsContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 140,
    gap: 16,
  },
  resultsFeaturedCard: {
    borderRadius: 18,
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#bfdbfe',
    padding: 16,
  },
  resultsFeaturedTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  resultsStatusBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#dcfce7',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
  },
  resultsStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#22c55e',
  },
  resultsStatusText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#166534',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  resultsFeaturedTitle: {
    marginTop: 10,
    fontSize: 24,
    fontWeight: '900',
    color: '#0b1b33',
  },
  resultsFeaturedDate: {
    marginTop: 6,
    fontSize: 14,
    fontWeight: '600',
    color: '#6b7280',
  },
  resultsFeaturedIconBox: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultsFeaturedIcon: {
    fontSize: 22,
  },
  resultsAssistCard: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 12,
    marginBottom: 12,
  },
  resultsAssistHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  resultsAssistIcon: {
    fontSize: 16,
    color: '#0b74ff',
  },
  resultsAssistLabel: {
    fontSize: 12,
    fontWeight: '900',
    color: '#0b74ff',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  resultsAssistText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  resultsFeaturedActions: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  resultsPrimaryAction: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#0b74ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultsPrimaryActionText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  resultsIconAction: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultsIconActionText: {
    fontSize: 18,
  },
  resultsSectionTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0b1b33',
    marginTop: 8,
  },
  resultsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
  },
  resultsRowIconBox: {
    width: 56,
    height: 56,
    borderRadius: 14,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultsRowIcon: {
    fontSize: 22,
  },
  resultsRowTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  resultsRowTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '900',
    color: '#0b1b33',
  },
  resultsRowDate: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '600',
    color: '#6b7280',
  },
  resultsBadgeReady: {
    fontSize: 10,
    fontWeight: '900',
    color: '#166534',
    backgroundColor: '#dcfce7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  resultsBadgePending: {
    fontSize: 10,
    fontWeight: '900',
    color: '#92400e',
    backgroundColor: '#fef3c7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  resultsDownloadBox: {
    borderRadius: 18,
    backgroundColor: '#111827',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  resultsDownloadIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultsDownloadIcon: {
    fontSize: 18,
  },
  resultsDownloadTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  resultsDownloadSubtitle: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.75)',
    fontSize: 12,
    fontWeight: '600',
  },
  resultsDownloadBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#0b74ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultsDownloadBtnText: {
    fontSize: 18,
    color: '#ffffff',
  },
  resultsDetailContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 120,
    gap: 16,
  },
  resultsDetailCard: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
  },
  resultsDetailTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0b1b33',
  },
  resultsDetailDate: {
    marginTop: 6,
    fontSize: 14,
    color: '#6b7280',
  },
  resultsDetailStatus: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#dcfce7',
    color: '#166534',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  resultsDetailSummary: {
    marginTop: 12,
    fontSize: 16,
    color: '#111827',
    lineHeight: 22,
  },
  resultsDetailButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
    marginBottom: 8,
  },
  resultsViewerContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 120,
    gap: 16,
  },
  idEmergencyBox: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
    marginBottom: 18,
  },
  idEmergencyIcon: {
    fontSize: 24,
    fontWeight: '900',
    color: '#b91c1c',
    marginRight: 10,
  },
  idEmergencyText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#b91c1c',
  },
  idWelcomeTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#0b1b33',
    marginBottom: 6,
  },
  idWelcomeSubtitle: {
    fontSize: 18,
    color: '#4b5563',
    lineHeight: 26,
    marginBottom: 24,
  },
  idFieldGroup: {
    marginBottom: 22,
  },
  idFieldLabel: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0b1b33',
    marginBottom: 10,
  },
  idNumberInput: {
    height: 64,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#d1d5db',
    paddingHorizontal: 16,
    fontSize: 24,
    fontWeight: '800',
    color: '#0b1b33',
  },
  idHint: {
    marginTop: 6,
    fontSize: 14,
    fontStyle: 'italic',
    color: '#6b7280',
  },
  idHelpButton: {
    marginTop: 12,
    alignSelf: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  idHelpText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0b74ff',
  },
  idSecurityRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  idSecurityIcon: {
    fontSize: 14,
  },
  idSecurityText: {
    fontSize: 14,
    color: '#6b7280',
  },
  warningBox: {
    borderRadius: 16,
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#fbbf24',
    padding: 14,
    marginBottom: 12,
  },
  warningTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#92400e',
  },
  warningText: {
    marginTop: 6,
    fontSize: 16,
    color: '#92400e',
    lineHeight: 22,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#f5f5f5'
  },
  buttonContainer: {
    width: '100%'
  },
  roleButton: {
    padding: 20,
    borderRadius: 12,
    marginBottom: 15,
    alignItems: 'center'
  },
  inputContainer: {
    width: '100%'
  },
  mainButton: {
    backgroundColor: '#333',
    padding: 18,
    borderRadius: 8,
    alignItems: 'center'
  },
  backText: {
    color: '#2196F3',
    textAlign: 'center',
    marginTop: 20,
    fontSize: 16
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 16,
    color: '#4b5563',
    marginBottom: 8,
    fontWeight: '600',
  }
});
